// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt9taf8TeLsoI4DheaE0bf0dPmN4c8t1w',
    appId: '1:986821887210:web:4896ab31b8f91f59798393',
    messagingSenderId: '986821887210',
    projectId: 'flutex-admin-f4583',
    authDomain: 'flutex-admin-f4583.firebaseapp.com',
    storageBucket: 'flutex-admin-f4583.firebasestorage.app',
    measurementId: 'G-K741TTFECF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXTnYxOvLkuJIhfWwh5rUZ58gJn-S4fEQ',
    appId: '1:986821887210:android:e9381cb49e81002a798393',
    messagingSenderId: '986821887210',
    projectId: 'flutex-admin-f4583',
    storageBucket: 'flutex-admin-f4583.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCODrvLV_goxekcL5yhEfSzwIoieNtq3UI',
    appId: '1:986821887210:ios:02101b44f62e31b0798393',
    messagingSenderId: '986821887210',
    projectId: 'flutex-admin-f4583',
    storageBucket: 'flutex-admin-f4583.firebasestorage.app',
    iosBundleId: 'com.flutex.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCODrvLV_goxekcL5yhEfSzwIoieNtq3UI',
    appId: '1:986821887210:ios:02101b44f62e31b0798393',
    messagingSenderId: '986821887210',
    projectId: 'flutex-admin-f4583',
    storageBucket: 'flutex-admin-f4583.firebasestorage.app',
    iosBundleId: 'com.flutex.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt9taf8TeLsoI4DheaE0bf0dPmN4c8t1w',
    appId: '1:986821887210:web:7e6722eb1b4a5c2b798393',
    messagingSenderId: '986821887210',
    projectId: 'flutex-admin-f4583',
    authDomain: 'flutex-admin-f4583.firebaseapp.com',
    storageBucket: 'flutex-admin-f4583.firebasestorage.app',
    measurementId: 'G-V5KHTEMJN1',
  );
}
